repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: "0.7.8"
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.12"
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: "25.1.0"
    hooks:
      - id: black
  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.20.0"
    hooks:
      - id: pyupgrade
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.16.0"
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports, --no-warn-unused-ignores]
        files: ^src/
        additional_dependencies: ["aiohttp>=3.8.0", "aiofiles>=23.0.0", "pydantic>=2.0.0"]
  - repo: local
    hooks:
      - id: generate-docs
        name: Generate API documentation
        entry: uv run pdoc registry_api_v2_client --output-dir docs-api
        language: system
        files: ^src/.*\.py$
        pass_filenames: false
        always_run: true